server:
  port: 8081

spring:
    application:
        name: zuul-server


eureka:
    server:
        url: localhost
        port: 7813
    client:
        healthcheck:
            enabled: true
        service-url:
            defaultZone: http://${eureka.server.url}:${eureka.server.port}/eureka/
    instance:
        lease-expiration-duration-in-seconds: 30
        lease-renewal-interval-in-seconds: 20
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
zuul:
    routes:
        user:
            path: /user/**
            serviceId: user-server
        team:
            path: /team/**
            serviceId: team-server
        store:
            path: /store/**
            serviceId: store-server
        player:
            path: /player/**
            serviceId: player-server
        message:
            path: /message/**
            serviceId: message-server
        game:
            path: /game/**
            serviceId: game-server
        place:
            path: /place/**
            serviceId: place-server
        photo:
            path: /photo/**
            serviceId: photo-server
        club:
            path: /club/**
            serviceId: club-server
        erueka:
            path: /erueka/**
            serviceId: erueka-server
        config:
            path: /config/**
            serviceId: config-server