server:
    port: 7815
spring:
    application:
        name: microservice-config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/goying666/config-server/
#                    username: 13040837899@163.com
#                    password: code666.
#                    label: master


eureka:
    server:
#        url: localhost
        url: 47.106.149.105
        port: 7813
    client:
        healthcheck:
            enabled: true
        service-url:
            defaultZone: http://${eureka.server.url}:${eureka.server.port}/eureka/
    instance:
        lease-expiration-duration-in-seconds: 30
        lease-renewal-interval-in-seconds: 20
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        prefer-ip-address: true